[package]
name = "volk"
version = "0.1.1"
edition = "2024"
license = "MIT"
authors = ["Thomas Habets <thomas@habets.se>"]
repository = "https://github.com/ThomasHabets/volk"
description = "Rust bindings for volk"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
