name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Rustup upgrade
      run: rustup install nightly
    - name: Install clippy
      run: rustup component add --toolchain nightly clippy
    - name: Cargo install
      run: cargo install cargo-deny tickbox
    - name: apt-get update
      run: sudo apt-get update
    - name: Install stuff
      run: sudo apt-get install libvolk-dev
    - name: Run tests
      run: NODIFF=true CLEANUP=true tickbox --dir tickbox/precommit --disable-tui --max-concurrency=1
